import { ArrowRight, BadgeCheck, FileText, Handshake, ShieldCheck, Target, TrendingUp } from "lucide-react";
import type { ReactNode } from "react";
import { buttonVariants } from "@/components/ui/button";
import { Reveal, SectionLabel } from "@/components/SiteShell";
import { MagicText } from "@/components/ui/magic-text";
import { BOOKING_URL } from "@/lib/siteLinks";

export default function About() { return <>
  <PageHero eyebrow="About SwitchYard FX" title={<>Manage FX risk<br /><span>with confidence.</span></>} copy="Partnering with CFOs to navigate FX uncertainty and unlock strategic value through tailored treasury solutions." />
  <section className="bg-white px-5 py-20 lg:px-8 lg:py-28" data-testid="about-mission-section"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[0.8fr_1.2fr]"><div className="lg:sticky lg:top-28 lg:self-start"><Reveal from="left"><SectionLabel>Our mission</SectionLabel><h2 className="text-4xl font-bold leading-tight tracking-[-0.04em] sm:text-5xl" data-testid="about-mission-heading">Make the complex feel <span className="text-[#52796F]">simple.</span></h2></Reveal></div>{/* Each word brightens as the mission scrolls into view. */}<div className="-mx-4 max-w-3xl space-y-6 text-[#12261F]" data-testid="about-mission-copy"><MagicText text="SwitchYard simplifies FX risk management for mid-market CFOs. We believe treasury teams deserve better – smarter solutions, clearer guidance, and genuine partnership." /><MagicText text="By combining deep FX expertise with intuitive tools and advisory, we help you make confident decisions that protect margins and unlock growth." /></div></div></section>
  <section className="bg-[#F5F7F6] px-5 py-20 lg:px-8 lg:py-24" data-testid="about-trust-section"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1fr_1.2fr] lg:items-center"><Reveal from="left"><div className="rounded-[2rem] bg-[#12261F] p-8 text-white sm:p-12"><div className="flex items-center gap-4"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-[#A8C5BA] text-[#12261F]"><Handshake size={27} /></div><div><p className="font-bold">A genuine partnership</p><p className="text-sm text-white/55">Built for the long view</p></div></div><p className="mt-10 text-2xl font-bold leading-snug">“The best risk strategy is one your whole business can understand.”</p><p className="mt-8 text-xs leading-5 text-white/45">Programme Manager under Ebury Partners Australia (AFSL 520548)</p></div></Reveal><Reveal from="right" delay={0.1}><SectionLabel>Trust, by design</SectionLabel><h2 className="max-w-xl text-4xl font-bold tracking-[-0.04em] sm:text-5xl" data-testid="trust-heading">20+ years of FX expertise behind every decision.</h2><p className="mt-6 max-w-xl leading-7 text-[#4A5A55]" data-testid="trust-copy">SwitchYard operates as a Programme Manager under Ebury Partners Australia Pty Ltd (AFSL 520548). This partnership ensures world-class execution, global FX expertise, and complete regulatory compliance. Every transaction is backed by Ebury’s institutional strength and 20+ years of FX market experience.</p><div className="mt-8 grid gap-3 sm:grid-cols-3">{[[ShieldCheck, "ASIC AR"], [BadgeCheck, "AFSL 520548"], [ShieldCheck, "AUSTRAC registered"]].map(([Icon, label]) => <div key={label as string} className="flex items-center gap-2 rounded-xl border border-[#DCE5E1] bg-white p-4 text-sm font-bold"><Icon size={17} className="text-[#2D6A4F]" />{label as string}</div>)}</div></Reveal></div></section>
  <ProcessSection /><section className="bg-[#12261F] px-5 py-20 text-white lg:px-8 lg:py-24"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 lg:flex-row lg:items-center"><div><SectionLabel>Let’s work together</SectionLabel><h2 className="text-4xl font-bold tracking-[-0.04em] sm:text-5xl" data-testid="about-cta-heading">Ready to get started?</h2><p className="mt-4 max-w-xl text-white/60">Schedule a free consultation with our FX specialists to discuss your treasury challenges.</p></div><a href={BOOKING_URL} target="_blank" rel="noreferrer" className={buttonVariants({ size: "lg" }) + " rounded-full bg-[#A8C5BA] text-[#12261F] hover:bg-white"} data-testid="about-book-consult-button">Book Consultation <ArrowRight size={17} /></a></div></section>
 </>; }

function PageHero({ eyebrow, title, copy }: { eyebrow: string; title: ReactNode; copy: string }) { return <section className="bg-[#12261F] px-5 py-20 text-white lg:px-8 lg:py-28" data-testid="page-hero"><div className="mx-auto max-w-7xl"><Reveal from="left"><SectionLabel>{eyebrow}</SectionLabel><h1 className="max-w-4xl text-5xl font-bold leading-[1.02] tracking-[-0.05em] sm:text-6xl" data-testid="page-hero-heading">{title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/60" data-testid="page-hero-copy">{copy}</p></Reveal></div></section>; }
function ProcessSection() { const steps = [[Target, "Assess", "Understand your FX exposures, business drivers, and risk appetite."], [Handshake, "Hedge", "Design and execute tailored hedging strategies."], [TrendingUp, "Track", "Monitor hedge performance in real-time dashboards."], [FileText, "Report", "Deliver board-ready insights and compliance documentation."]]; return <section className="bg-white px-5 py-20 lg:px-8 lg:py-28" data-testid="about-process-section"><div className="mx-auto max-w-7xl"><Reveal from="left"><SectionLabel>Our process</SectionLabel><h2 className="text-4xl font-bold tracking-[-0.04em] sm:text-5xl" data-testid="about-process-heading">A simple path to better certainty.</h2></Reveal><div className="mt-12 grid gap-4 md:grid-cols-4">{steps.map(([Icon, title, copy], index) => <Reveal key={title as string} from="scale" delay={index * 0.06} className="h-full"><div className="h-full rounded-2xl border border-[#DCE5E1] p-6" data-testid={`about-process-step-${index + 1}`}><span className="text-xs font-bold text-[#52796F]">0{index + 1}</span><Icon className="mt-10 text-[#2D6A4F]" size={23} /><h3 className="mt-6 text-xl font-bold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-[#4A5A55]">{copy as string}</p></div></Reveal>)}</div></div></section>; }