import { ArrowLeft, ArrowRight, CalendarDays, Clock3 } from "lucide-react";
import { Link } from "react-router-dom";
import { buttonVariants } from "@/components/ui/button";
import { Reveal, SectionLabel } from "@/components/SiteShell";
import { BOOKING_URL } from "@/lib/siteLinks";

export default function Article() { return <>
  <section className="bg-[#12261F] px-5 py-20 text-white lg:px-8 lg:py-28" data-testid="article-hero"><div className="mx-auto max-w-4xl"><Link to="/insights" className="inline-flex items-center gap-2 text-sm font-bold text-[#A8C5BA]" data-testid="article-back-link"><ArrowLeft size={15} /> Back to insights</Link><Reveal><div className="mt-14 flex gap-2"><span className="rounded-full bg-white/15 px-3 py-1 text-xs font-bold">AUD/USD</span><span className="rounded-full bg-[#A8C5BA] px-3 py-1 text-xs font-bold text-[#12261F]">Bearish</span></div><h1 className="mt-6 text-5xl font-bold leading-[1.02] tracking-[-0.05em] sm:text-6xl" data-testid="article-heading">AUD weakness extends against USD</h1><div className="mt-8 flex flex-wrap gap-5 text-sm text-white/55"><span className="flex items-center gap-2"><CalendarDays size={15} />12 Feb 2026</span><span className="flex items-center gap-2"><Clock3 size={15} />5 min read</span></div></Reveal></div></section>
  <article className="bg-white px-5 py-20 lg:px-8 lg:py-28" data-testid="article-content"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[0.7fr_1.3fr]"><aside><div className="sticky top-28 rounded-2xl bg-[#F5F7F6] p-6"><p className="text-xs font-bold uppercase tracking-[0.15em] text-[#52796F]">In this article</p><div className="mt-5 grid gap-3 text-sm font-bold text-[#4A5A55]"><a href="#context">Market context</a><a href="#treasury">What treasury teams should consider</a><a href="#next">The next decision</a></div></div></aside><div className="max-w-2xl text-lg leading-8 text-[#4A5A55]"><SectionLabel>SwitchYard FX analysis</SectionLabel><p className="text-2xl font-bold leading-9 text-[#12261F]">The Australian dollar has softened against the US dollar, bringing the conversation back to what finance teams can control: exposure, timing and a policy that is clear before the market moves.</p><h2 id="context" className="mt-14 text-3xl font-bold text-[#12261F]">Market context</h2><p className="mt-5">Currency markets are rarely linear. A weaker Australian dollar can create pressure for importers while improving the translated value of offshore revenue. The useful question is not whether the next move can be predicted — it is whether your business has a decision framework ready.</p><div className="my-10 rounded-2xl border-l-4 border-[#2D6A4F] bg-[#E8EEEB] p-6 text-xl font-bold leading-8 text-[#12261F]">“Good risk management makes uncertainty easier to carry — it does not pretend uncertainty is gone.”</div><h2 id="treasury" className="mt-14 text-3xl font-bold text-[#12261F]">What treasury teams should consider</h2><p className="mt-5">Start by separating committed exposures from forecast exposures, then map each to the commercial outcome you are trying to protect. A forward contract, option structure or staged approach may each be appropriate in a different scenario.</p><ul className="mt-6 grid gap-3 text-base"><li className="flex gap-3"><span className="mt-2 h-2 w-2 shrink-0 rounded-full bg-[#2D6A4F]" />Which cashflows are certain, and when?</li><li className="flex gap-3"><span className="mt-2 h-2 w-2 shrink-0 rounded-full bg-[#2D6A4F]" />What outcome would make the next budget easier to defend?</li><li className="flex gap-3"><span className="mt-2 h-2 w-2 shrink-0 rounded-full bg-[#2D6A4F]" />How will the board see the trade-off?</li></ul><h2 id="next" className="mt-14 text-3xl font-bold text-[#12261F]">The next decision</h2><p className="mt-5">A 15-minute conversation can help you turn a moving market into a clearer set of options. We will bring the questions; you bring the context.</p><a href={BOOKING_URL} target="_blank" rel="noreferrer" className={buttonVariants({ size: "lg" }) + " mt-8 rounded-full bg-[#2D6A4F] text-white"} data-testid="article-book-consult-button">Talk to an FX specialist <ArrowRight size={17} /></a></div></div></article>
 </>; }