import { ArrowRight, CalendarDays, Clock3, Download, Mail, MapPin, MessageCircle, Phone, QrCode, ShieldCheck } from "lucide-react";
import { buttonVariants } from "@/components/ui/button";
import { LeadForm } from "@/components/LeadCapture";
import { Reveal, SectionLabel } from "@/components/SiteShell";
import { BOOKING_URL, EMAIL, EMAIL_HREF, HEDGE_POLICY_PDF, PHONE_DISPLAY, PHONE_HREF, WECHAT_ID, WHATSAPP_URL } from "@/lib/siteLinks";

export default function Contact() { return <>
  <section className="bg-[#12261F] px-5 py-20 text-white lg:px-8 lg:py-24" data-testid="contact-hero"><div className="mx-auto max-w-7xl"><Reveal from="left"><SectionLabel>Contact</SectionLabel><h1 className="max-w-4xl text-5xl font-bold leading-[1.02] tracking-[-0.05em] sm:text-6xl" data-testid="contact-heading">Let’s talk<br /><span className="text-[#A8C5BA]">FX strategy.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/60" data-testid="contact-description">Book a consultation, ask questions, or discuss your specific FX challenges with our team.</p></Reveal></div></section>
  <section className="bg-[#F5F7F6] px-5 py-20 lg:px-8 lg:py-28" data-testid="schedule-section"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[1.1fr_0.9fr]"><Reveal from="left" className="h-full"><div className="h-full overflow-hidden rounded-[2rem] border border-[#DCE5E1] bg-white" data-testid="cal-booking-card"><div className="flex items-center justify-between border-b border-[#DCE5E1] p-6"><div><p className="font-bold">Schedule a call</p><p className="mt-1 max-w-md text-sm text-[#4A5A55]">Book a 15-minute strategy call with our FX specialists. We’ll help you understand your exposure, explore hedging options, and answer any questions about our services.</p></div><CalendarDays className="text-[#2D6A4F]" /></div><iframe title="SwitchYard FX booking calendar" src={BOOKING_URL} loading="lazy" className="h-[390px] w-full border-0 bg-white" data-testid="cal-booking-embed" /><div className="border-t border-[#DCE5E1] p-6"><a href={BOOKING_URL} target="_blank" rel="noreferrer" className={buttonVariants({ size: "lg" }) + " w-full justify-center rounded-full bg-[#2D6A4F] text-white"} data-testid="view-calendar-book-button">View Calendar & Book <ArrowRight size={17} /></a></div></div></Reveal><Reveal from="right" delay={0.1} className="h-full"><div className="flex h-full flex-col rounded-[2rem] bg-[#12261F] p-8 text-white sm:p-10"><SectionLabel>Before we meet</SectionLabel><h2 className="text-3xl font-bold" data-testid="resources-heading">Make the first conversation count.</h2><div className="mb-8 mt-8 grid gap-3"><a href={HEDGE_POLICY_PDF} download className="flex items-center gap-4 rounded-2xl border border-white/10 bg-white/5 p-5 text-left transition-colors hover:bg-white/10" data-testid="contact-guide-resource"><Download className="text-[#A8C5BA]" /><span><span className="block font-bold">Download the Hedge Policy Guide</span><span className="mt-1 block text-xs text-white/50">Sample treasury policy template (PDF)</span></span></a></div><div className="mt-auto border-t border-white/10 pt-6"><p className="text-xs text-white/50">Available times</p><p className="mt-2 flex items-center gap-2 font-bold"><Clock3 size={15} className="text-[#A8C5BA]" /> Mon–Fri · 9am–5pm AEDT</p></div></div></Reveal></div></section>
  <section className="bg-white px-5 py-20 lg:px-8 lg:py-24" data-testid="connect-section"><div className="mx-auto max-w-7xl"><Reveal from="left"><SectionLabel>Other ways to connect</SectionLabel><h2 className="text-4xl font-bold tracking-[-0.04em] sm:text-5xl" data-testid="connect-heading">Pick your preferred channel.</h2></Reveal><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-6">{([[Phone, "Call us", PHONE_DISPLAY, PHONE_HREF, "Mon–Fri, 9am–5pm AEDT"], [Mail, "Email", EMAIL, EMAIL_HREF, "Response within 2 hours"], [MessageCircle, "WhatsApp", "+61 2 7226 3680", WHATSAPP_URL, "Quick questions & urgent issues"], [QrCode, "WeChat", `ID: ${WECHAT_ID}`, undefined, "Search our ID in WeChat to connect"], [MapPin, "Location", "Sydney, Australia", undefined, "Meetings by appointment"]] as const).map(([Icon, label, detail, href, note], index) => <a key={label} href={href} target={href?.startsWith("http") ? "_blank" : undefined} rel="noreferrer" className={`${index < 3 ? "lg:col-span-2" : index === 3 ? "lg:col-span-3" : "sm:col-span-2 lg:col-span-3"} h-full rounded-2xl border border-[#DCE5E1] p-6 transition-all duration-300 hover:-translate-y-1 hover:shadow-xl`} data-testid={`connect-card-${String(label).toLowerCase().replaceAll(" ", "-")}`}><Icon className="text-[#2D6A4F]" size={23} /><p className="mt-8 text-sm font-bold text-[#4A5A55]">{label}</p><p className="mt-2 break-words font-bold">{detail}</p><p className="mt-2 text-xs text-[#4A5A55]">{note}</p></a>)}</div></div></section>
  <section className="bg-[#12261F] px-5 py-20 text-white lg:px-8 lg:py-28" data-testid="message-section"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[0.8fr_1.2fr]"><Reveal from="left"><SectionLabel>Send us a message</SectionLabel><h2 className="text-4xl font-bold tracking-[-0.04em] sm:text-5xl" data-testid="message-heading">Tell us where you want more certainty.</h2><p className="mt-6 max-w-md leading-7 text-white/60">Share a little context and we will connect you with the right specialist.</p><div className="mt-10 flex items-center gap-3 text-sm text-white/60"><ShieldCheck className="text-[#A8C5BA]" size={19} /> Your details stay confidential.</div></Reveal><Reveal from="right" delay={0.1}><div className="rounded-[2rem] border border-white/10 bg-white/5 p-6 sm:p-8"><LeadForm kind="contact" showVolume /></div></Reveal></div></section>
  <section className="bg-[#F5F7F6] px-5 py-12 lg:px-8" data-testid="contact-legal-section"><div className="mx-auto flex max-w-7xl gap-3 text-xs leading-5 text-[#4A5A55]"><ShieldCheck size={16} className="mt-0.5 shrink-0 text-[#2D6A4F]" /><p>Switchyard Capital Pty Ltd is an Authorised Representative (ASIC AR No. 001318359) of Ebury Partners Australia Pty Limited (ACN 632 570 702), AFSL 520548. This information is general in nature and does not constitute financial advice.</p></div></section>
 </>; }
