import { useEffect, useRef, useState, type MouseEvent } from "react";
import { useQuery } from "@tanstack/react-query";
import { motion, useInView, useMotionValue, useReducedMotion, useSpring, useTransform } from "motion/react";
import { ArrowRight, ArrowUpRight, Check, ChevronRight, CircleDollarSign, FileText, Gauge, Globe2, HandCoins, Layers3, LineChart, LockKeyhole, Radar, ShieldCheck, Sparkles, Target, TrendingUp, Users } from "lucide-react";
import { Link } from "react-router-dom";
import type { FxRate, MarketQuote } from "@/lib/types";
import { switchyardService } from "@/services/switchyard";
import { buttonVariants, Button } from "@/components/ui/button";
import { GuideDialog } from "@/components/LeadCapture";
import { Reveal, SectionLabel } from "@/components/SiteShell";
import { BOOKING_URL, WHATSAPP_URL } from "@/lib/siteLinks";

const fallbackRates = [
  { pair: "AUD/USD", rate: 0.6512, change: 0.48, source: "fallback" as const },
  { pair: "AUD/EUR", rate: 0.6018, change: -0.27, source: "fallback" as const },
  { pair: "AUD/GBP", rate: 0.5129, change: 0.92, source: "fallback" as const },
];
const dashboardData = { EUR: { cashflow: "€1.24M", ratio: 98 }, GBP: { cashflow: "£980K", ratio: 92 }, USD: { cashflow: "$1.86M", ratio: 96 } };
const chartRanges = { "2H": 8, "4H": 16, "6H": 24, "1D": 32 } as const;

function normaliseChart(values: number[]) {
  if (!values.length) return [50, 52, 48, 55, 58, 54, 62, 66];
  const min = Math.min(...values);
  const max = Math.max(...values);
  if (max === min) return values.map(() => 55);
  return values.map((value) => 24 + ((value - min) / (max - min)) * 62);
}

export default function Home() {
  const [currency, setCurrency] = useState<keyof typeof dashboardData>("EUR");
  const [horizon, setHorizon] = useState<keyof typeof chartRanges>("4H");
  const [guideOpen, setGuideOpen] = useState(false);
  const marketQuery = useQuery({ queryKey: ["market-overview"], queryFn: switchyardService.getMarketOverview, retry: false, staleTime: 60_000, refetchInterval: 60_000 });
  const rates: FxRate[] = (marketQuery.data?.quotes ?? fallbackRates).map((quote) => ({ ...quote, source: marketQuery.data?.source ?? "fallback" }));
  const current = dashboardData[currency];
  const quote = (marketQuery.data?.quotes ?? fallbackRates).find((item) => item.pair === `AUD/${currency}`) ?? fallbackRates[0];
  const closes = marketQuery.data?.candles.map((candle) => candle.close) ?? [];
  const points = normaliseChart(closes.slice(-chartRanges[horizon]));

  return <>
    <section className="relative isolate overflow-hidden bg-[#12261F] text-white" data-testid="home-hero-section">
      <div className="hero-grid absolute inset-0 opacity-25" />
      <motion.div className="absolute -right-40 -top-40 h-[34rem] w-[34rem] rounded-full bg-[#2D6A4F]/35 blur-[110px]" animate={{ scale: [1, 1.12, 1], opacity: [0.45, 0.7, 0.45] }} transition={{ duration: 9, repeat: Infinity, ease: "easeInOut" }} />
      <div className="absolute -bottom-24 left-[12%] h-72 w-72 rounded-full bg-[#A8C5BA]/10 blur-[90px]" />
      <div className="relative mx-auto grid min-h-svh max-w-7xl grid-cols-[minmax(0,1fr)] gap-14 px-5 pb-20 pt-32 lg:grid-cols-[0.88fr_1.12fr] lg:items-center lg:px-8 lg:pb-24 lg:pt-32">
        <motion.div className="relative z-10 min-w-0" initial={{ opacity: 0, x: -24 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.7, ease: "easeOut" }}>
          <div className="mb-7 inline-flex items-center gap-2 rounded-full border border-[#A8C5BA]/30 bg-white/[0.06] px-3 py-2 text-[11px] font-bold tracking-[0.18em] text-[#A8C5BA] backdrop-blur-md" data-testid="hero-badge"><span className="relative flex h-2 w-2"><span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-[#A8C5BA] opacity-60" /><span className="relative h-2 w-2 rounded-full bg-[#A8C5BA]" /></span> FOR MID-MARKET CFOs</div>
          <h1 className="max-w-2xl text-5xl font-bold leading-[0.96] tracking-[-0.055em] sm:text-6xl lg:text-[4.65rem]" data-testid="hero-heading">Manage FX risk<br /><span className="text-[#A8C5BA]">with confidence.</span></h1>
          <p className="mt-7 max-w-xl text-lg leading-8 text-white/65" data-testid="hero-description">Tailored corporate FX solutions that protect your margins and simplify treasury management.</p>
          <div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href={BOOKING_URL} target="_blank" rel="noreferrer" className={buttonVariants({ size: "lg" }) + " group justify-center rounded-full bg-[#2D6A4F] px-6 text-white shadow-[0_12px_40px_rgba(45,106,79,.3)] hover:bg-[#3d8163]"} data-testid="hero-book-consult-button">Book a 15-Min Consult <ArrowRight size={17} className="transition-transform group-hover:translate-x-1" /></a><Button variant="outline" onClick={() => setGuideOpen(true)} className="h-12 rounded-full border-white/20 bg-white/[0.03] px-6 text-white backdrop-blur-sm hover:bg-white/10 hover:text-white" data-testid="hero-download-policy-button">Download Hedge Policy</Button></div>
          <div className="mt-10 grid gap-4 border-t border-white/10 pt-6 sm:grid-cols-3">{[[ShieldCheck, "Expert Analysis"], [LockKeyhole, "Risk Protection"], [Sparkles, "15-Min Setup"]].map(([Icon, label]) => <div key={label as string} className="flex items-center gap-2 text-sm text-white/70" data-testid={`hero-point-${String(label).toLowerCase().replaceAll(" ", "-")}`}><Icon size={16} className="text-[#A8C5BA]" />{label as string}</div>)}</div>
          <p className="mt-7 text-[11px] leading-5 text-white/40" data-testid="hero-disclaimer">This information is general in nature and does not constitute financial advice.</p>
        </motion.div>
        <MarketCommandCentre currency={currency} setCurrency={setCurrency} horizon={horizon} setHorizon={setHorizon} current={current} points={points} quote={quote} quotes={marketQuery.data?.quotes ?? fallbackRates} source={marketQuery.data?.source ?? "fallback"} provider={marketQuery.data?.provider ?? "Indicative fallback"} warning={marketQuery.data?.warning} />
      </div>
      <div className="hero-fade absolute inset-x-0 bottom-0 h-24" />
    </section>
    <RateStrip rates={rates} isLoading={marketQuery.isLoading} source={marketQuery.data?.source ?? "fallback"} />
    <CfoOutcomes />
    <MetricBand />
    <section className="bg-[#F5F7F6] px-5 py-20 lg:px-8 lg:py-28" data-testid="solutions-section"><div className="mx-auto max-w-7xl"><Reveal><SectionLabel>Corporate FX solutions</SectionLabel><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><h2 className="max-w-2xl text-4xl font-bold leading-tight tracking-[-0.04em] sm:text-5xl" data-testid="solutions-heading">Manage your finances<br /><span className="text-[#52796F]">with ease.</span></h2><p className="max-w-md text-[#4A5A55]" data-testid="solutions-description">Comprehensive treasury services designed for mid-market enterprises managing multi-currency exposure.</p></div></Reveal><div className="mt-12 grid gap-4 md:grid-cols-3">{[[CircleDollarSign, "Competitive rates with full transparency", "Simple to use and enhanced reporting to help you make smarter decisions."], [Globe2, "24/7 online platform access", "Robust and fully secure payment infrastructure to enable reliable transfers across the globe."], [Users, "Dedicated account manager", "Transact seamlessly using the online platform or with the help of your dedicated relationship manager."]].map(([Icon, title, text], index) => <Reveal key={title as string} delay={index * 0.07}><div className="group rounded-2xl border border-[#DCE5E1] bg-white p-7 shadow-sm transition-all duration-300 hover:-translate-y-1 hover:shadow-xl" data-testid={`solution-card-${index + 1}`}><div className="mb-14 grid h-12 w-12 place-items-center rounded-xl bg-[#E8EEEB] text-[#2D6A4F] transition-colors group-hover:bg-[#2D6A4F] group-hover:text-white"><Icon size={23} /></div><h3 className="text-xl font-bold" data-testid={`solution-title-${index + 1}`}>{title as string}</h3><p className="mt-3 text-sm leading-6 text-[#4A5A55]" data-testid={`solution-copy-${index + 1}`}>{text as string}</p><ChevronRight size={20} className="mt-7 text-[#2D6A4F] transition-transform group-hover:translate-x-1" /></div></Reveal>)}</div></div></section>
    <section className="bg-white px-5 py-20 lg:px-8 lg:py-28" data-testid="advisory-section"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1fr_0.9fr] lg:items-center"><Reveal><div className="relative overflow-hidden rounded-[2rem] bg-[#E8EEEB] p-8 sm:p-12"><div className="absolute -right-10 -top-10 h-44 w-44 rounded-full bg-[#A8C5BA]/50 blur-2xl" /><div className="relative"><div className="flex items-center justify-between"><span className="rounded-full bg-white px-3 py-2 text-xs font-bold text-[#2D6A4F]">MARKET INTELLIGENCE</span><LineChart className="text-[#52796F]" /></div><div className="mt-20 grid grid-cols-6 items-end gap-3"><div className="h-14 rounded-t-lg bg-[#A8C5BA]" /><div className="h-24 rounded-t-lg bg-[#52796F]" /><div className="h-20 rounded-t-lg bg-[#2D6A4F]" /><div className="h-36 rounded-t-lg bg-[#12261F]" /><div className="h-28 rounded-t-lg bg-[#52796F]" /><div className="h-44 rounded-t-lg bg-[#2D6A4F]" /></div><div className="mt-5 flex justify-between text-xs text-[#4A5A55]"><span>Jan</span><span>Feb</span><span>Mar</span><span>Apr</span><span>May</span><span>Jun</span></div></div></div></Reveal><Reveal delay={0.1}><SectionLabel>Advisory, not guesswork</SectionLabel><h2 className="max-w-xl text-4xl font-bold leading-tight tracking-[-0.04em] sm:text-5xl" data-testid="advisory-heading">Grow your business with <span className="text-[#52796F]">expert FX advisory.</span></h2><p className="mt-6 max-w-lg leading-7 text-[#4A5A55]" data-testid="advisory-description">We have helped thousands of businesses trade and thrive globally. Get in touch with our team to learn how we can help you succeed beyond borders.</p><a href={BOOKING_URL} target="_blank" rel="noreferrer" className={buttonVariants({ size: "lg" }) + " mt-8 rounded-full bg-[#2D6A4F] text-white hover:bg-[#3d8163]"} data-testid="advisory-book-button">Book a 15-min call <ArrowUpRight size={17} /></a></Reveal></div></section>
    <ExposureScenarios />
    <section className="bg-[#F5F7F6] px-5 py-20 lg:px-8 lg:py-24" data-testid="lending-section"><div className="mx-auto grid max-w-7xl gap-8 rounded-[2rem] bg-[#12261F] p-8 text-white sm:p-12 lg:grid-cols-[1.15fr_0.85fr] lg:items-end"><div><SectionLabel>Business lending</SectionLabel><h2 className="max-w-2xl text-4xl font-bold leading-tight tracking-[-0.04em] sm:text-5xl" data-testid="lending-heading">Flexible lending solutions to help you realise your ambitions.</h2></div><div><p className="text-white/60" data-testid="lending-description">Access a fast and hassle-free trade finance facility when needed to fund your purchases.</p><Link to="/contact" className="mt-7 inline-flex items-center gap-2 font-bold text-[#A8C5BA] hover:text-white" data-testid="lending-explore-link">Explore more <ArrowRight size={16} /></Link></div></div></section>
    <HowWeWork />
    <section className="bg-[#12261F] px-5 py-20 text-white lg:px-8 lg:py-24" data-testid="guide-section"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1fr_0.8fr] lg:items-center"><Reveal><SectionLabel>Free resource</SectionLabel><h2 className="max-w-2xl text-4xl font-bold leading-tight tracking-[-0.04em] sm:text-5xl" data-testid="guide-heading">Get the free Hedge Policy Guide.</h2><p className="mt-5 max-w-xl text-white/60" data-testid="guide-description">Download our sample treasury policy template and learn how to build a hedging framework that works for mid-market CFOs.</p><Button onClick={() => setGuideOpen(true)} className="mt-8 h-12 rounded-full bg-[#A8C5BA] px-6 font-bold text-[#12261F] hover:bg-white" data-testid="guide-open-button">Download PDF <ArrowRight size={17} /></Button></Reveal><Reveal delay={0.1}><div className="grid gap-3">{["Policy structure & governance best practices", "Currency pair prioritisation framework", "Reporting & board communication templates"].map((item) => <div key={item} className="flex items-center gap-4 rounded-2xl border border-white/10 bg-white/5 p-5 backdrop-blur-sm" data-testid={`guide-feature-${item.toLowerCase().replaceAll(" ", "-")}`}><div className="grid h-9 w-9 place-items-center rounded-full bg-[#2D6A4F]"><Check size={17} /></div><span className="font-bold">{item}</span></div>)}</div></Reveal></div></section>
    <InsightsPreview />
    <section className="bg-[#E8EEEB] px-5 py-20 lg:px-8 lg:py-24" data-testid="final-cta-section"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><SectionLabel>Start the conversation</SectionLabel><h2 className="max-w-2xl text-4xl font-bold tracking-[-0.04em] sm:text-5xl" data-testid="final-cta-heading">Ready to transform your treasury?</h2><p className="mt-4 text-[#4A5A55]" data-testid="final-cta-description">Schedule a 15-minute consultation with our FX specialists. No obligation. Just expert advice tailored to your situation.</p></div><div className="flex flex-col gap-3 sm:flex-row"><a href={BOOKING_URL} target="_blank" rel="noreferrer" className={buttonVariants({ size: "lg" }) + " justify-center rounded-full bg-[#2D6A4F] text-white hover:bg-[#3d8163]"} data-testid="final-book-consult-button">Book Consultation <ArrowRight size={17} /></a><a href={WHATSAPP_URL} target="_blank" rel="noreferrer" className={buttonVariants({ variant: "outline", size: "lg" }) + " justify-center rounded-full border-[#2D6A4F] text-[#2D6A4F]"} data-testid="final-whatsapp-button">WhatsApp Us</a></div></div></section>
    <GuideDialog open={guideOpen} onOpenChange={setGuideOpen} />
  </>;
}

function MarketCommandCentre({ currency, setCurrency, horizon, setHorizon, current, points, quote, quotes, source, provider, warning }: { currency: keyof typeof dashboardData; setCurrency: (value: keyof typeof dashboardData) => void; horizon: keyof typeof chartRanges; setHorizon: (value: keyof typeof chartRanges) => void; current: typeof dashboardData.EUR; points: number[]; quote: MarketQuote; quotes: MarketQuote[]; source: "live" | "fallback"; provider: "Twelve Data" | "Indicative fallback"; warning?: string | null }) {
  const reducedMotion = useReducedMotion();
  const pointerX = useMotionValue(0);
  const pointerY = useMotionValue(0);
  const smoothX = useSpring(pointerX, { stiffness: 130, damping: 22 });
  const smoothY = useSpring(pointerY, { stiffness: 130, damping: 22 });
  const rotateY = useTransform(smoothX, [-0.5, 0.5], [-3, 3]);
  const rotateX = useTransform(smoothY, [-0.5, 0.5], [3, -3]);
  const xAt = (index: number) => 18 + index * (285 / Math.max(points.length - 1, 1));
  const path = points.map((point, index) => `${index === 0 ? "M" : "L"} ${xAt(index)} ${170 - point * 1.35}`).join(" ");

  function handlePointer(event: MouseEvent<HTMLDivElement>) {
    if (reducedMotion) return;
    const bounds = event.currentTarget.getBoundingClientRect();
    pointerX.set((event.clientX - bounds.left) / bounds.width - 0.5);
    pointerY.set((event.clientY - bounds.top) / bounds.height - 0.5);
  }

  return <motion.div className="relative z-10 mx-auto w-full min-w-0 max-w-[650px] py-6 lg:py-0" initial={{ opacity: 0, scale: 0.96, x: 24 }} animate={{ opacity: 1, scale: 1, x: 0 }} transition={{ duration: 0.75, delay: 0.12, ease: "easeOut" }} onMouseMove={handlePointer} onMouseLeave={() => { pointerX.set(0); pointerY.set(0); }} data-testid="hero-dashboard-card">
    <motion.div className="relative overflow-hidden rounded-[2rem] border border-white/15 bg-[#173229]/90 p-5 shadow-[0_35px_90px_rgba(0,0,0,.35)] backdrop-blur-2xl sm:p-7" style={reducedMotion ? undefined : { rotateX, rotateY, transformPerspective: 1200 }}>
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_0%,rgba(168,197,186,.18),transparent_36%)]" />
      <div className="relative flex items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-[10px] font-bold tracking-[0.18em] text-[#A8C5BA]"><Radar size={14} /> LIVE MARKET COMMAND</div><p className="mt-2 text-sm text-white/45">AUD crosses · 15-minute pricing</p></div><div className={`flex items-center gap-2 rounded-full border px-3 py-2 text-[10px] font-bold ${source === "live" ? "border-[#6EE7A8]/25 bg-[#6EE7A8]/10 text-[#6EE7A8]" : "border-amber-200/20 bg-amber-200/10 text-amber-100"}`} data-testid="hero-market-source"><span className={`h-1.5 w-1.5 rounded-full ${source === "live" ? "animate-pulse bg-[#6EE7A8]" : "bg-amber-200"}`} /> {source === "live" ? "LIVE · TWELVE DATA" : "INDICATIVE"}</div></div>
      <div className="relative mt-6 flex gap-2 overflow-x-auto border-b border-white/10 pb-4">{Object.keys(dashboardData).map((value) => <button type="button" key={value} onClick={() => setCurrency(value as keyof typeof dashboardData)} className={`rounded-full px-4 py-2 text-xs font-bold transition-[background-color,color,transform] duration-200 hover:-translate-y-0.5 ${currency === value ? "bg-[#A8C5BA] text-[#12261F]" : "bg-white/[0.04] text-white/50 hover:text-white"}`} data-testid={`dashboard-currency-${value.toLowerCase()}-tab`}>{value}</button>)}</div>
      <div className="relative mt-6 grid gap-5 sm:grid-cols-[1fr_auto]"><div><p className="text-xs text-white/45">AUD/{currency} spot</p><div className="mt-2 flex items-end gap-3"><p className="text-4xl font-bold tracking-[-0.04em]" data-testid="dashboard-cashflow-value">{quote.rate.toFixed(4)}</p><p className={`mb-1 rounded-full px-2 py-1 text-[10px] font-bold ${quote.change >= 0 ? "bg-[#6EE7A8]/10 text-[#6EE7A8]" : "bg-red-300/10 text-red-200"}`}>{quote.change >= 0 ? "↗" : "↘"} {Math.abs(quote.change).toFixed(2)}%</p></div><p className="mt-2 text-[10px] text-white/35">Example exposure · {current.cashflow}</p></div><div className="flex items-center gap-3 rounded-2xl border border-white/10 bg-black/10 px-4 py-3"><div className="relative grid h-12 w-12 place-items-center rounded-full" style={{ background: `conic-gradient(#A8C5BA ${current.ratio}%, rgba(255,255,255,.08) 0)` }}><div className="grid h-9 w-9 place-items-center rounded-full bg-[#173229] text-[11px] font-bold" data-testid="dashboard-hedge-ratio">{current.ratio}%</div></div><div><p className="text-[10px] text-white/40">Hedge ratio</p><p className="text-xs font-bold">Example portfolio</p></div></div></div>
      <div className="relative mt-7 rounded-2xl border border-white/10 bg-[#10271F]/70 p-4"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><p className="text-xs font-bold">AUD/USD intraday</p><p className="mt-1 text-[10px] text-white/40">15-minute candles · current session</p></div><div className="flex rounded-full border border-white/10 bg-white/[0.03] p-1">{Object.keys(chartRanges).map((value) => <button type="button" key={value} onClick={() => setHorizon(value as keyof typeof chartRanges)} className={`rounded-full px-2.5 py-1 text-[9px] font-bold transition-colors ${horizon === value ? "bg-white/15 text-[#A8C5BA]" : "text-white/35 hover:text-white"}`} data-testid={`dashboard-horizon-${value.toLowerCase()}-toggle`}>{value}</button>)}</div></div><svg viewBox="0 0 320 185" className="mt-3 h-40 w-full overflow-visible" role="img" aria-label="AUD/USD 15-minute live market chart"><defs><linearGradient id="exposure-fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#A8C5BA" stopOpacity=".38" /><stop offset="100%" stopColor="#A8C5BA" stopOpacity="0" /></linearGradient></defs><path d={`${path} L 303 178 L 18 178 Z`} fill="url(#exposure-fill)" /><motion.path key={`${horizon}-${points.length}`} d={path} fill="none" stroke="#A8C5BA" strokeWidth="3" strokeLinecap="round" initial={{ pathLength: 0 }} animate={{ pathLength: 1 }} transition={{ duration: reducedMotion ? 0 : 0.8, ease: "easeOut" }} />{points.map((point, index) => <motion.circle key={index} cx={xAt(index)} cy={170 - point * 1.35} r={points.length > 18 ? "2" : "3.5"} fill="#E8EEEB" initial={{ scale: 0 }} animate={{ scale: 1 }} transition={{ delay: reducedMotion ? 0 : Math.min(index * 0.025, 0.5) }} />)}</svg><div className="flex justify-between text-[9px] text-white/30"><span>Session open</span><span>{horizon} view</span><span>Latest</span></div>{warning && <p className="mt-2 text-[9px] text-amber-100/70" data-testid="hero-market-warning">{warning}</p>}</div>
      <div className="relative mt-4 overflow-hidden rounded-xl border border-white/[0.07] bg-white/[0.03] py-3"><div className="market-ticker flex w-max items-center gap-8 px-4 text-[10px] font-bold text-white/50">{[...quotes, ...quotes].map((item, index) => <span key={`${item.pair}-${index}`}>{item.pair} <b className={item.change >= 0 ? "text-[#6EE7A8]" : "text-red-300"}>{item.rate.toFixed(4)} {item.change >= 0 ? "+" : ""}{item.change.toFixed(2)}%</b></span>)}<span>{provider.toUpperCase()}</span></div></div>
    </motion.div>
  </motion.div>;
}

function CfoOutcomes() {
  const outcomes = [
    [Layers3, "One source of truth", "Bring exposures, hedge positions and upcoming settlements into one decision-ready view."],
    [ShieldCheck, "Margins stay protected", "Set guardrails before volatility arrives, with structures aligned to commercial outcomes."],
    [Gauge, "Board-ready clarity", "Turn treasury activity into a concise story leadership can understand and act on."],
  ] as const;
  return <section className="section-transition bg-[#F5F7F6] px-5 py-20 lg:px-8 lg:py-28" data-testid="cfo-outcomes-section"><div className="mx-auto max-w-7xl"><Reveal><div className="grid gap-8 lg:grid-cols-[0.75fr_1.25fr] lg:items-end"><div><SectionLabel>Built around CFO outcomes</SectionLabel><h2 className="text-4xl font-bold leading-tight tracking-[-0.045em] sm:text-5xl" data-testid="cfo-outcomes-heading">Less market noise.<br /><span className="text-[#52796F]">More decision quality.</span></h2></div><p className="max-w-xl text-lg leading-8 text-[#4A5A55]">Your FX programme should make the business easier to run. Every recommendation starts with the margin, cashflow and reporting outcome you need.</p></div></Reveal><div className="mt-14 grid gap-4 md:grid-cols-3">{outcomes.map(([Icon, title, copy], index) => <Reveal key={title} delay={index * 0.08}><motion.div whileHover={{ y: -7 }} transition={{ type: "spring", stiffness: 280, damping: 22 }} className="group relative min-h-72 overflow-hidden rounded-[1.5rem] border border-[#DCE5E1] bg-white p-7 shadow-[0_12px_40px_rgba(18,38,31,.04)]" data-testid={`cfo-outcome-card-${index + 1}`}><div className="absolute -right-12 -top-12 h-36 w-36 rounded-full bg-[#E8EEEB] transition-transform duration-500 group-hover:scale-125" /><div className="relative grid h-12 w-12 place-items-center rounded-xl bg-[#12261F] text-[#A8C5BA]"><Icon size={22} /></div><p className="relative mt-16 text-[10px] font-bold tracking-[0.16em] text-[#52796F]">OUTCOME 0{index + 1}</p><h3 className="relative mt-3 text-2xl font-bold">{title}</h3><p className="relative mt-3 text-sm leading-6 text-[#4A5A55]">{copy}</p></motion.div></Reveal>)}</div></div></section>;
}

function AnimatedCounter({ value, suffix = "", prefix = "" }: { value: number; suffix?: string; prefix?: string }) {
  const ref = useRef<HTMLSpanElement>(null);
  const inView = useInView(ref, { once: true, margin: "-60px" });
  const reducedMotion = useReducedMotion();
  const [display, setDisplay] = useState(0);
  useEffect(() => {
    if (!inView) return;
    if (reducedMotion) { setDisplay(value); return; }
    let frame = 0;
    const start = performance.now();
    const tick = (now: number) => {
      const progress = Math.min((now - start) / 1200, 1);
      setDisplay(Math.round(value * (1 - Math.pow(1 - progress, 3))));
      if (progress < 1) frame = requestAnimationFrame(tick);
    };
    frame = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(frame);
  }, [inView, reducedMotion, value]);
  return <span ref={ref}>{prefix}{display}{suffix}</span>;
}

function MetricBand() {
  return <section className="dark-surface relative overflow-hidden bg-[#12261F] px-5 py-16 text-white lg:px-8" data-testid="animated-metrics-section"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_100%,rgba(82,121,111,.22),transparent_48%)]" /><div className="relative mx-auto grid max-w-7xl gap-8 sm:grid-cols-2 lg:grid-cols-4">{[[20, "+", "Years of FX market experience through Ebury"], [24, "/7", "Online platform access"], [5, "", "Core FX solutions"], [15, " min", "To start the conversation"]].map(([value, suffix, label], index) => <Reveal key={label as string} delay={index * 0.06}><div className="border-l border-white/10 pl-5" data-testid={`metric-${index + 1}`}><p className="text-4xl font-bold tracking-[-0.05em] text-[#A8C5BA]"><AnimatedCounter value={value as number} suffix={suffix as string} /></p><p className="mt-2 text-sm text-white/55">{label as string}</p></div></Reveal>)}</div></section>;
}

function ExposureScenarios() {
  const scenarios = {
    Conservative: { hedge: 90, certainty: "High", flexibility: "Low", outcome: "$48k protected", copy: "Prioritise forecast certainty with a higher hedge ratio across committed exposures." },
    Balanced: { hedge: 70, certainty: "Balanced", flexibility: "Balanced", outcome: "$34k protected", copy: "Blend protection and participation with staged forwards and selective option structures." },
    Flexible: { hedge: 45, certainty: "Moderate", flexibility: "High", outcome: "$22k protected", copy: "Keep more upside participation while placing a clear floor under the downside." },
  } as const;
  const [selected, setSelected] = useState<keyof typeof scenarios>("Balanced");
  const current = scenarios[selected];
  return <section className="section-transition bg-[#F5F7F6] px-5 py-20 lg:px-8 lg:py-28" data-testid="exposure-scenarios-section"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><Reveal><SectionLabel>Explore the trade-off</SectionLabel><h2 className="text-4xl font-bold leading-tight tracking-[-0.045em] sm:text-5xl" data-testid="exposure-scenarios-heading">See how different hedge settings change the conversation.</h2><p className="mt-6 max-w-lg leading-7 text-[#4A5A55]">Switch between indicative approaches to compare certainty, flexibility and protected value. A real strategy would be tailored to your cashflows and risk appetite.</p><div className="mt-8 flex flex-wrap gap-2" role="tablist" aria-label="Exposure scenarios">{Object.keys(scenarios).map((name) => <button type="button" role="tab" aria-selected={selected === name} key={name} onClick={() => setSelected(name as keyof typeof scenarios)} className={`rounded-full border px-5 py-3 text-sm font-bold transition-[background-color,color,border-color,transform] duration-200 hover:-translate-y-0.5 ${selected === name ? "border-[#2D6A4F] bg-[#2D6A4F] text-white" : "border-[#DCE5E1] bg-white text-[#4A5A55]"}`} data-testid={`scenario-${name.toLowerCase()}-tab`}>{name}</button>)}</div></Reveal><Reveal delay={0.1}><motion.div key={selected} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="overflow-hidden rounded-[2rem] border border-[#DCE5E1] bg-white shadow-[0_24px_70px_rgba(18,38,31,.08)]" data-testid="scenario-result-card"><div className="grid gap-6 border-b border-[#DCE5E1] p-7 sm:grid-cols-[1fr_auto] sm:p-9"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#52796F]">{selected} approach</p><p className="mt-3 text-3xl font-bold" data-testid="scenario-protected-outcome">{current.outcome}</p><p className="mt-3 max-w-md text-sm leading-6 text-[#4A5A55]">{current.copy}</p></div><div className="relative grid h-28 w-28 place-items-center rounded-full" style={{ background: `conic-gradient(#2D6A4F ${current.hedge}%, #E8EEEB 0)` }}><div className="grid h-20 w-20 place-items-center rounded-full bg-white text-center"><span className="text-2xl font-bold">{current.hedge}%</span><span className="text-[9px] font-bold uppercase tracking-wide text-[#52796F]">hedged</span></div></div></div><div className="grid sm:grid-cols-2"><div className="border-b border-[#DCE5E1] p-6 sm:border-b-0 sm:border-r"><p className="text-xs text-[#4A5A55]">Cashflow certainty</p><p className="mt-2 text-lg font-bold">{current.certainty}</p></div><div className="p-6"><p className="text-xs text-[#4A5A55]">Upside flexibility</p><p className="mt-2 text-lg font-bold">{current.flexibility}</p></div></div></motion.div></Reveal></div></section>;
}

function RateStrip({ rates, isLoading, source }: { rates: FxRate[]; isLoading: boolean; source: "live" | "fallback" }) {
  return <section className="border-b border-[#DCE5E1] bg-white px-5 py-7 lg:px-8" data-testid="live-rates-section"><div className="mx-auto flex max-w-7xl flex-col gap-5 xl:flex-row xl:items-center"><div className="flex shrink-0 items-center gap-3"><span className="h-2.5 w-2.5 animate-pulse rounded-full bg-[#2D6A4F]" /><div><p className="text-sm font-bold">Live FX rates</p><p className="text-xs text-[#4A5A55]">Indicative market view · {isLoading ? "Updating" : source === "live" ? "Updated live" : "Indicative fallback"}</p></div></div><div className="grid flex-1 gap-3 sm:grid-cols-3">{rates.slice(0, 3).map((rate) => <div key={rate.pair} className="flex items-center justify-between rounded-xl border border-[#DCE5E1] bg-[#F5F7F6] px-4 py-3" data-testid={`rate-card-${rate.pair.replace("/", "-")}`}><div><p className="text-xs font-bold text-[#4A5A55]">{rate.pair}</p><p className="mt-1 font-bold">{rate.rate.toFixed(4)}</p></div><span className={`text-xs font-bold ${rate.change >= 0 ? "text-[#2D6A4F]" : "text-red-600"}`}>{rate.change >= 0 ? "+" : ""}{rate.change.toFixed(2)}%</span></div>)}</div></div></section>;
}

function HowWeWork() { const steps = [[Target, "01", "Assess", "We analyse your FX exposure, cash flows, and risk tolerance to understand your unique situation."], [HandCoins, "02", "Hedge", "Design and execute tailored strategies. Forward contracts, options, or custom structures."], [TrendingUp, "03", "Track", "Real-time monitoring and reporting. Transparent dashboards showing P&L and position management."], [FileText, "04", "Report", "Monthly compliance and strategy reviews. Ongoing optimisations based on market conditions."]]; return <section className="bg-white px-5 py-20 lg:px-8 lg:py-28" data-testid="how-we-work-section"><div className="mx-auto max-w-7xl"><Reveal><SectionLabel>How we work</SectionLabel><h2 className="max-w-xl text-4xl font-bold tracking-[-0.04em] sm:text-5xl" data-testid="how-we-work-heading">Clarity at every step.</h2></Reveal><div className="mt-12 grid gap-5 md:grid-cols-4">{steps.map(([Icon, number, title, copy], index) => <Reveal key={title as string} delay={index * 0.06}><div className="relative border-t-2 border-[#DCE5E1] pt-5" data-testid={`how-step-${number}`}><div className="flex items-center justify-between"><span className="text-xs font-bold text-[#52796F]">{number as string}</span><Icon size={20} className="text-[#2D6A4F]" /></div><h3 className="mt-10 text-xl font-bold">{title as string}</h3><p className="mt-3 text-sm leading-6 text-[#4A5A55]">{copy as string}</p></div></Reveal>)}</div></div></section>; }

function InsightsPreview() { return <section className="bg-[#F5F7F6] px-5 py-20 lg:px-8 lg:py-28" data-testid="market-commentary-section"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><SectionLabel>Market commentary</SectionLabel><h2 className="text-4xl font-bold tracking-[-0.04em] sm:text-5xl" data-testid="market-commentary-heading">A sharper read on the market.</h2></div><Link to="/insights" className="inline-flex items-center gap-2 font-bold text-[#2D6A4F]" data-testid="market-commentary-view-all">View all insights <ArrowRight size={16} /></Link></div><div className="mt-12 grid gap-5 md:grid-cols-3">{[["AUD/USD", "AUD weakness extends against USD", "The latest move is a reminder to separate market noise from your hedge plan."], ["EUR/AUD", "What changing rate cycles mean for importers", "Three questions finance teams should ask before the next settlement window."], ["Strategy", "A more useful way to think about hedge ratios", "Move beyond a single number and connect policy to cashflow certainty."]].map(([tag, title, copy], index) => <Reveal key={title} delay={index * 0.06}><Link to="/insights" className="group block rounded-2xl border border-[#DCE5E1] bg-white p-6 transition-all duration-300 hover:-translate-y-1 hover:shadow-xl" data-testid={`commentary-card-${index + 1}`}><span className="text-xs font-bold uppercase tracking-[0.15em] text-[#52796F]">{tag}</span><h3 className="mt-12 text-xl font-bold leading-snug group-hover:text-[#2D6A4F]">{title}</h3><p className="mt-3 text-sm leading-6 text-[#4A5A55]">{copy}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-[#2D6A4F]">Read more <ArrowRight size={15} /></span></Link></Reveal>)}</div></div></section>; }