import { CalendarClock, FileText } from "lucide-react";
import { LeadForm } from "@/components/LeadCapture";
import { Reveal, SectionLabel } from "@/components/SiteShell";
import { BOOKING_URL, HEDGE_POLICY_PDF } from "@/lib/siteLinks";

export default function Insights() { return <>
  <section className="bg-[#12261F] px-5 py-20 text-white lg:px-8 lg:py-24" data-testid="insights-hero"><div className="mx-auto max-w-7xl"><Reveal><SectionLabel>Market insights</SectionLabel><h1 className="max-w-4xl text-5xl font-bold leading-[1.02] tracking-[-0.05em] sm:text-6xl" data-testid="insights-heading">Stay ahead of<br /><span className="text-[#A8C5BA]">the next move.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/60" data-testid="insights-description">Curated FX insights, trends and analysis to support better treasury decisions.</p></Reveal></div></section>
  <section className="bg-[#F5F7F6] px-5 py-20 lg:px-8 lg:py-28" data-testid="insights-coming-soon-section"><div className="mx-auto grid max-w-7xl gap-6 lg:grid-cols-[1.3fr_0.7fr]"><Reveal className="h-full"><div className="flex h-full flex-col justify-between rounded-[2rem] bg-[#2D6A4F] p-8 text-white sm:p-12" data-testid="insights-coming-soon-card"><span className="w-fit rounded-full bg-white/15 px-3 py-1 text-xs font-bold">Coming soon</span><div className="mt-20 max-w-xl"><h2 className="text-3xl font-bold leading-tight sm:text-4xl" data-testid="insights-coming-soon-heading">Our market commentary is on its way.</h2><p className="mt-4 max-w-lg text-white/70">We’re preparing regular FX commentary, policy moves and practical recommendations for treasury teams. Subscribe below to get it as soon as it’s published.</p></div></div></Reveal><Reveal delay={0.1} className="h-full"><div className="flex h-full flex-col rounded-[2rem] border border-[#DCE5E1] bg-white p-7 sm:p-9" data-testid="insights-meanwhile"><SectionLabel>In the meantime</SectionLabel><div className="mt-6 grid gap-4"><a href={HEDGE_POLICY_PDF} download className="group flex gap-4 rounded-2xl border border-[#DCE5E1] p-5 transition-colors hover:border-[#2D6A4F]" data-testid="insights-guide-link"><FileText className="shrink-0 text-[#2D6A4F]" size={22} /><span><span className="block font-bold group-hover:text-[#2D6A4F]">Download the Hedge Policy Guide</span><span className="mt-1 block text-sm text-[#4A5A55]">Sample treasury policy template (PDF)</span></span></a><a href={BOOKING_URL} target="_blank" rel="noreferrer" className="group flex gap-4 rounded-2xl border border-[#DCE5E1] p-5 transition-colors hover:border-[#2D6A4F]" data-testid="insights-book-link"><CalendarClock className="shrink-0 text-[#2D6A4F]" size={22} /><span><span className="block font-bold group-hover:text-[#2D6A4F]">Talk to an FX specialist</span><span className="mt-1 block text-sm text-[#4A5A55]">Book a free 15-minute consultation</span></span></a></div></div></Reveal></div></section>
  <section className="bg-[#12261F] px-5 py-20 text-white lg:px-8 lg:py-24" data-testid="newsletter-section"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><div><SectionLabel>Stay informed</SectionLabel><h2 className="text-4xl font-bold tracking-[-0.04em] sm:text-5xl" data-testid="newsletter-heading">Stay ahead with<br /><span className="text-[#A8C5BA]">daily updates.</span></h2><p className="mt-5 text-white/60">Subscribe for daily commentary, policy moves, and strategic recommendations.</p></div><div><LeadForm kind="newsletter" showNewsletterFields /></div></div></section>
 </>; }
