import { useState } from "react";
import { ArrowRight, ArrowUpRight, Bell, Check, Clock3, Linkedin, Search, TrendingDown, TrendingUp } from "lucide-react";
import { Link } from "react-router-dom";
import { Button, buttonVariants } from "@/components/ui/button";
import { LeadForm } from "@/components/LeadCapture";
import { Reveal, SectionLabel } from "@/components/SiteShell";

const posts = [
  { tag: "AUD/USD", title: "AUD weakness extends against USD", excerpt: "What the latest move means for Australian importers and the decisions to make before the next settlement window.", tone: "Bearish", date: "12 Feb 2026" },
  { tag: "EUR/AUD", title: "Three ways to plan around rate uncertainty", excerpt: "A practical framework for finance teams balancing forecast certainty with flexibility.", tone: "Strategy", date: "05 Feb 2026" },
  { tag: "Strategy", title: "Hedge ratios are not a strategy", excerpt: "Why the most useful policy connects market risk to commercial cashflow, not a single target number.", tone: "Insight", date: "29 Jan 2026" },
  { tag: "USD", title: "The cost of waiting for a better rate", excerpt: "A calm look at timing risk, opportunity cost and what your policy can control.", tone: "Strategy", date: "22 Jan 2026" },
  { tag: "GBP/AUD", title: "When volatility becomes a planning tool", excerpt: "Turn a moving market into clearer scenarios for your next budget cycle.", tone: "Insight", date: "14 Jan 2026" },
  { tag: "CNY", title: "Keeping Asia-Pacific payments moving", excerpt: "The operational details that help treasury teams protect margin across new corridors.", tone: "Insight", date: "08 Jan 2026" },
];
const filters = ["All", "AUD/USD", "EUR/AUD", "Strategy", "USD", "GBP/AUD", "CNY", "AUD", "NZD/AUD", "CAD"];

export default function Insights() { const [filter, setFilter] = useState("All"); const [count, setCount] = useState(3); const filtered = filter === "All" ? posts : posts.filter((post) => post.tag === filter); const visible = filtered.slice(0, count); return <>
  <section className="bg-[#12261F] px-5 py-20 text-white lg:px-8 lg:py-24" data-testid="insights-hero"><div className="mx-auto max-w-7xl"><Reveal><SectionLabel>Market insights</SectionLabel><h1 className="max-w-4xl text-5xl font-bold leading-[1.02] tracking-[-0.05em] sm:text-6xl" data-testid="insights-heading">Stay ahead of<br /><span className="text-[#A8C5BA]">the next move.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/60" data-testid="insights-description">Curated FX insights, trends and analysis to support better treasury decisions.</p></Reveal></div></section>
  <section className="bg-[#E8EEEB] px-5 py-4 lg:px-8" data-testid="insights-login-banner"><div className="mx-auto flex max-w-7xl flex-col gap-3 py-2 text-sm sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><Bell size={16} className="text-[#2D6A4F]" /><span>Log in to personalise your market insights feed.</span></div><Link to="/login" className="font-bold text-[#2D6A4F]" data-testid="insights-login-link">Log in <ArrowRight className="inline" size={14} /></Link></div></section>
  <section className="bg-[#F5F7F6] px-5 py-20 lg:px-8 lg:py-28" data-testid="featured-insight-section"><div className="mx-auto grid max-w-7xl gap-6 lg:grid-cols-[1.3fr_0.7fr]"><Reveal><Link to="/insights/aud-weakness-extends" className="group block min-h-[360px] rounded-[2rem] bg-[#2D6A4F] p-8 text-white transition-transform duration-300 hover:-translate-y-1 sm:p-12" data-testid="featured-insight-card"><div className="flex items-start justify-between"><div className="flex gap-2"><span className="rounded-full bg-white/15 px-3 py-1 text-xs font-bold">AUD/USD</span><span className="rounded-full bg-[#A8C5BA] px-3 py-1 text-xs font-bold text-[#12261F]">Bearish</span></div><ArrowUpRight className="text-[#A8C5BA]" /></div><div className="mt-28 max-w-xl"><p className="text-sm text-white/60">Featured analysis · 12 Feb 2026</p><h2 className="mt-3 text-3xl font-bold leading-tight sm:text-4xl">AUD weakness extends against USD</h2><p className="mt-4 max-w-lg text-white/70">What the latest move means for Australian importers and the decisions to make before the next settlement window.</p><span className="mt-6 inline-flex items-center gap-2 font-bold">Read more <ArrowRight size={16} /></span></div></Link></Reveal><Reveal delay={0.1}><div className="h-full rounded-[2rem] border border-[#DCE5E1] bg-white p-7 sm:p-9" data-testid="trending-topics"><SectionLabel>Trending now</SectionLabel><div className="mt-8 grid gap-6">{["The case for a board-ready hedge policy", "AUD outlook: what changed this quarter", "Can zero-cost structures keep flexibility?", "Treasury reporting that gets read"].map((topic, index) => <Link key={topic} to="/insights/market-commentary" className="group flex gap-4" data-testid={`trending-topic-${index + 1}`}><span className="text-sm font-bold text-[#A8C5BA]">0{index + 1}</span><span className="font-bold leading-snug group-hover:text-[#2D6A4F]">{topic}</span></Link>)}</div></div></Reveal></div></section>
  <section className="bg-white px-5 py-20 lg:px-8 lg:py-24" data-testid="insights-feed-section"><div className="mx-auto max-w-7xl"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><SectionLabel>Earlier posts</SectionLabel><h2 className="text-4xl font-bold tracking-[-0.04em] sm:text-5xl" data-testid="earlier-posts-heading">Useful context.<br />No market noise.</h2></div><div className="flex gap-2 overflow-auto pb-1" data-testid="insights-filter-list">{filters.map((value) => <button type="button" key={value} onClick={() => { setFilter(value); setCount(3); }} className={`whitespace-nowrap rounded-full border px-4 py-2 text-xs font-bold transition-colors ${filter === value ? "border-[#2D6A4F] bg-[#2D6A4F] text-white" : "border-[#DCE5E1] text-[#4A5A55] hover:border-[#2D6A4F]"}`} data-testid={`insights-filter-${value.toLowerCase().replaceAll("/", "-").replaceAll(" ", "-")}`}>{value}</button>)}</div></div><div className="mt-12 grid gap-5 md:grid-cols-3">{visible.map((post, index) => <Reveal key={post.title} delay={index * 0.04}><Link to="/insights/aud-weakness-extends" className="group block rounded-2xl border border-[#DCE5E1] p-6 transition-all duration-300 hover:-translate-y-1 hover:shadow-xl" data-testid={`insight-post-card-${index + 1}`}><div className="flex items-center justify-between text-xs"><span className="font-bold uppercase tracking-[0.15em] text-[#52796F]">{post.tag}</span><span className="flex items-center gap-1 text-[#4A5A55]"><Clock3 size={13} />{post.date}</span></div><h3 className="mt-12 text-xl font-bold leading-snug group-hover:text-[#2D6A4F]">{post.title}</h3><p className="mt-3 text-sm leading-6 text-[#4A5A55]">{post.excerpt}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-[#2D6A4F]">Read more <ArrowRight size={15} /></span></Link></Reveal>)}</div>{visible.length < filtered.length && <div className="mt-10 text-center"><Button variant="outline" onClick={() => setCount((value) => value + 3)} className="rounded-full border-[#2D6A4F] text-[#2D6A4F]" data-testid="insights-load-more-button">Load More</Button></div>}</div></section>
  <section className="bg-[#F5F7F6] px-5 py-20 lg:px-8 lg:py-24" data-testid="switchyard-take-section"><div className="mx-auto max-w-7xl"><div className="flex items-end justify-between"><div><SectionLabel>SwitchYard’s take</SectionLabel><h2 className="text-4xl font-bold tracking-[-0.04em] sm:text-5xl" data-testid="switchyard-take-heading">Straight from our advisors.</h2></div><Linkedin className="hidden text-[#2D6A4F] sm:block" /></div><div className="mt-12 grid gap-5 md:grid-cols-2"><AdvisorPost name="Michael Boulton" role="FX Advisor" copy="A hedge policy does not have to predict the market. It has to give your business a plan when the market moves." /><AdvisorPost name="James Ellery" role="Treasury Specialist" copy="The strongest treasury teams make risk visible early — then make the next decision feel simple." /></div></div></section>
  <section className="bg-[#12261F] px-5 py-20 text-white lg:px-8 lg:py-24" data-testid="newsletter-section"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><div><SectionLabel>Stay informed</SectionLabel><h2 className="text-4xl font-bold tracking-[-0.04em] sm:text-5xl" data-testid="newsletter-heading">Market insight,<br /><span className="text-[#A8C5BA]">on your terms.</span></h2><p className="mt-5 text-white/60">Choose your role and get the signal without the noise.</p></div><div><LeadForm kind="newsletter" showNewsletterFields /></div></div></section>
 </>; }

function AdvisorPost({ name, role, copy }: { name: string; role: string; copy: string }) { return <div className="rounded-2xl border border-[#DCE5E1] bg-white p-7" data-testid={`advisor-post-${name.toLowerCase().replaceAll(" ", "-")}`}><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-full bg-[#E8EEEB] font-bold text-[#2D6A4F]">{name.split(" ").map((part) => part[0]).join("")}</div><div><p className="font-bold">{name}</p><p className="text-xs text-[#4A5A55]">{role}</p></div></div><p className="mt-7 text-lg font-bold leading-7">“{copy}”</p><p className="mt-5 text-sm font-bold text-[#2D6A4F]">#treasury #FXstrategy #SwitchYardFX</p></div>; }