import { ArrowRight, Banknote, BriefcaseBusiness, ChartNoAxesCombined, Check, CircleDollarSign, ShieldCheck } from "lucide-react";
import { Link } from "react-router-dom";
import { buttonVariants } from "@/components/ui/button";
import { Reveal, SectionLabel } from "@/components/SiteShell";
import { BOOKING_URL } from "@/lib/siteLinks";

const services = [
  { icon: Banknote, title: "Forward Contracts", copy: "Forward contracts provide certainty for your FX exposures by locking in exchange rates today for future settlements. Ideal for businesses with predictable cross-border cash flows.", cta: "Request Pricing",
    benefits: ["Eliminates FX uncertainty on forecasted exposures", "Customisable maturity dates and amounts", "No upfront premium required", "Transparent pricing with competitive rates"],
    uses: ["Overseas supplier payments", "Forecast revenue hedging", "M&A transaction costs", "Dividend repatriation"] },
  { icon: ShieldCheck, title: "Options & Zero Cost Structures", copy: "Options and zero-cost collar strategies give you asymmetric risk profiles – protecting against downside while preserving profit potential when markets move in your favour.", cta: "Request Pricing",
    benefits: ["Caps adverse FX moves while retaining upside", "Flexible premium structures", "Customisable strike prices", "Suited to strategic deals and M&A"],
    uses: ["Earnings protection", "Tender bid defence", "Strategic international expansion", "Seasonal exposure management"] },
  { icon: CircleDollarSign, title: "Payments & Settlements", copy: "Streamlined cross-border payment solutions with highly competitive rates and transparent fees. Through our partnership with Ebury, we provide access to pricing typically reserved for larger institutions, delivered without the traditional institutional complexity.", cta: "Learn More",
    benefits: ["Competitive FX pricing", "Fast settlement (same-day or T+1)", "Transparent fee structure", "Multi-currency capabilities"],
    uses: ["Cross-border supplier payments", "Dividend repatriation", "International receivables", "Bank transfers and wire instructions"] },
  { icon: ChartNoAxesCombined, title: "Risk Strategy Advisory", copy: "Our advisory team works with you to design hedging policies, frameworks, and reporting structures that align with your risk appetite and business objectives.", cta: "Book Consultation",
    benefits: ["Custom hedging policy development", "Scenario analysis & stress testing", "Board-level reporting frameworks", "Ongoing strategy optimisation"],
    uses: ["Hedging policy development", "Treasury KPI design", "Compliance documentation", "Board reporting standards"] },
  { icon: BriefcaseBusiness, title: "Treasury Support", copy: "On-demand treasury support for your most complex FX challenges. Our specialists provide real-time market insights and transaction structuring expertise.", cta: "Request Support",
    benefits: ["Real-time market insights", "Complex transaction structuring", "Deal support & negotiation", "Execution oversight"],
    uses: ["Large M&A hedging", "Multi-currency restructuring", "Financing optimisation", "Refinancing FX strategies"] },
];

export default function Services() { return <>
  <section className="bg-[#12261F] px-5 py-20 text-white lg:px-8 lg:py-28" data-testid="services-hero"><div className="mx-auto max-w-7xl"><Reveal><SectionLabel>What we do</SectionLabel><h1 className="max-w-5xl text-5xl font-bold leading-[1.02] tracking-[-0.05em] sm:text-6xl" data-testid="services-heading">Corporate FX<br /><span className="text-[#A8C5BA]">solutions.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/60" data-testid="services-description">Tailored strategies for mid-market CFOs. Every solution is built for your business, not a one-size-fits-all approach.</p></Reveal></div></section>
  <section className="bg-[#F5F7F6] px-5 py-20 lg:px-8 lg:py-28" data-testid="services-list-section"><div className="mx-auto max-w-7xl"><div className="grid gap-4">{services.map(({ icon: Icon, title, copy, cta, benefits, uses }, index) => <Reveal key={title} delay={index * 0.04}><div className="group grid gap-8 rounded-2xl border border-[#DCE5E1] bg-white p-7 transition-all duration-300 hover:-translate-y-1 hover:shadow-xl md:grid-cols-[72px_1fr_auto] md:items-start" data-testid={`service-card-${index + 1}`}><div className="grid h-14 w-14 place-items-center rounded-2xl bg-[#E8EEEB] text-[#2D6A4F] transition-colors group-hover:bg-[#2D6A4F] group-hover:text-white"><Icon size={25} /></div><div><h2 className="text-2xl font-bold" data-testid={`service-title-${index + 1}`}>{title}</h2><p className="mt-2 max-w-2xl leading-7 text-[#4A5A55]">{copy}</p><div className="mt-6 grid gap-6 sm:grid-cols-2">{([["Key benefits", benefits], ["Use cases", uses]] as const).map(([heading, items]) => <div key={heading}><p className="text-xs font-bold uppercase tracking-[0.15em] text-[#52796F]">{heading}</p><ul className="mt-3 grid gap-2 text-sm text-[#4A5A55]">{items.map((item) => <li key={item} className="flex gap-2"><Check size={16} className="mt-0.5 shrink-0 text-[#2D6A4F]" />{item}</li>)}</ul></div>)}</div></div><Link to="/contact" className="inline-flex items-center gap-2 whitespace-nowrap font-bold text-[#2D6A4F]" data-testid={`service-cta-${index + 1}`}>{cta} <ArrowRight size={16} /></Link></div></Reveal>)}</div></div></section>
  <section className="bg-white px-5 py-20 lg:px-8 lg:py-24" data-testid="services-cta-section"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 rounded-[2rem] bg-[#E8EEEB] p-8 sm:p-12 lg:flex-row lg:items-center"><div><SectionLabel>Need a steer?</SectionLabel><h2 className="text-4xl font-bold tracking-[-0.04em] sm:text-5xl" data-testid="services-cta-heading">Not sure which solution fits?</h2><p className="mt-4 text-[#4A5A55]">Book a free consultation with our FX specialists to discuss your unique needs.</p></div><a href={BOOKING_URL} target="_blank" rel="noreferrer" className={buttonVariants({ size: "lg" }) + " rounded-full bg-[#2D6A4F] text-white hover:bg-[#3d8163]"} data-testid="services-book-consult-button">Book a free consultation <ArrowRight size={17} /></a></div></section>
 </>; }