import { ArrowRight, Banknote, BriefcaseBusiness, CalendarClock, ChartNoAxesCombined, CircleDollarSign, HandCoins, ShieldCheck } from "lucide-react";
import { Link } from "react-router-dom";
import { buttonVariants } from "@/components/ui/button";
import { Reveal, SectionLabel } from "@/components/SiteShell";

const services = [[Banknote, "Forward Contracts", "Lock in exchange rates for future cross-border transactions and protect your expected margin.", "Request Pricing"], [ShieldCheck, "Options & Zero Cost Structures", "Build downside protection while keeping the upside when the market moves in your favour.", "Request Pricing"], [CircleDollarSign, "Payments & Settlements", "Make cross-border payments with competitive institutional pricing through Ebury.", "Learn More"], [ChartNoAxesCombined, "Risk Strategy Advisory", "Create custom hedging policies, frameworks and reporting for your business.", "Book Consultation"], [BriefcaseBusiness, "Treasury Support", "Get on-demand expertise and real-time market guidance when decisions matter.", "Request Support"]] as const;

export default function Services() { return <>
  <section className="bg-[#12261F] px-5 py-20 text-white lg:px-8 lg:py-28" data-testid="services-hero"><div className="mx-auto max-w-7xl"><Reveal><SectionLabel>What we do</SectionLabel><h1 className="max-w-5xl text-5xl font-bold leading-[1.02] tracking-[-0.05em] sm:text-6xl" data-testid="services-heading">Corporate FX<br /><span className="text-[#A8C5BA]">solutions.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/60" data-testid="services-description">Tailored strategies for mid-market CFOs. Every solution is built for your business, not a one-size-fits-all approach.</p></Reveal></div></section>
  <section className="bg-[#F5F7F6] px-5 py-20 lg:px-8 lg:py-28" data-testid="services-list-section"><div className="mx-auto max-w-7xl"><div className="grid gap-4">{services.map(([Icon, title, copy, cta], index) => <Reveal key={title} delay={index * 0.04}><div className="group grid gap-8 rounded-2xl border border-[#DCE5E1] bg-white p-7 transition-all duration-300 hover:-translate-y-1 hover:shadow-xl md:grid-cols-[72px_1fr_auto] md:items-center" data-testid={`service-card-${index + 1}`}><div className="grid h-14 w-14 place-items-center rounded-2xl bg-[#E8EEEB] text-[#2D6A4F] transition-colors group-hover:bg-[#2D6A4F] group-hover:text-white"><Icon size={25} /></div><div><h2 className="text-2xl font-bold" data-testid={`service-title-${index + 1}`}>{title}</h2><p className="mt-2 max-w-2xl leading-7 text-[#4A5A55]">{copy}</p></div><Link to="/contact" className="inline-flex items-center gap-2 whitespace-nowrap font-bold text-[#2D6A4F]" data-testid={`service-cta-${index + 1}`}>{cta} <ArrowRight size={16} /></Link></div></Reveal>)}</div></div></section>
  <section className="bg-white px-5 py-20 lg:px-8 lg:py-24" data-testid="services-cta-section"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 rounded-[2rem] bg-[#E8EEEB] p-8 sm:p-12 lg:flex-row lg:items-center"><div><SectionLabel>Need a steer?</SectionLabel><h2 className="text-4xl font-bold tracking-[-0.04em] sm:text-5xl" data-testid="services-cta-heading">Not sure which solution fits?</h2><p className="mt-4 text-[#4A5A55]">A free 15-minute consultation can help you find the right starting point.</p></div><a href="https://cal.com/" target="_blank" rel="noreferrer" className={buttonVariants({ size: "lg" }) + " rounded-full bg-[#2D6A4F] text-white hover:bg-[#3d8163]"} data-testid="services-book-consult-button">Book a free consultation <ArrowRight size={17} /></a></div></section>
 </>; }